# Netlify Configuration
[build]
  publish = "dist"
  command = "npm run build"

[functions]
  directory = "netlify/functions"

# Edge Functions for global performance
[[edge_functions]]
  function = "analyze"
  path = "/api/analyze"

# Environment variables (set in Netlify dashboard)
# AZURE_OPENAI_ENDPOINT=https://your-resource.openai.azure.com
# AZURE_OPENAI_API_KEY=your-api-key
# AZURE_OPENAI_DEPLOYMENT=your-deployment-name

# Headers for CORS
[[headers]]
  for = "/api/*"
  [headers.values]
    Access-Control-Allow-Origin = "*"
    Access-Control-Allow-Methods = "GET, POST, OPTIONS"
    Access-Control-Allow-Headers = "Content-Type, Authorization, x-api-key"

# Redirects
[[redirects]]
  from = "/health"
  to = "/.netlify/functions/analyze"
  status = 200